# make sure your solution is assigned to the answer variable so the tests can work!
answer = {char: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ' for char in range(65,91)}
print(answer) 
# {65: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 66: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 
# 67: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 68: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 
# 69: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 70: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 
# 71: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 72: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 
# 73: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 74: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 
# 75: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 76: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 
# 77: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 78: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 
# 79: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 80: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 
# 81: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 82: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 
# 83: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 84: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 
# 85: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 86: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 
# 87: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 88: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 
# 89: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 90: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'}

print("\n")
###############

#Use chr() on the numbers between 65 and 91:

answer2 = {count: chr(count) for count in range(65,91)} 
print(answer2) 
 # {65: 'A', 66: 'B', 67: 'C', 68: 'D', 69: 'E', 70: 'F', 71: 'G', 72: 'H', 
 # 73: 'I', 74: 'J', 75: 'K', 76: 'L', 77: 'M', 78: 'N', 79: 'O', 80: 'P', 
 # 81: 'Q', 82: 'R', 83: 'S', 84: 'T', 85: 'U', 86: 'V', 87: 'W', 88: 'X', 
 # 89: 'Y', 90: 'Z'}